<footer>

  <p>
    <a href="https://cos-10026-assignment-group-2.atlassian.net/jira/software/projects/SCRUM/summary">
      Jira Project Link
    </a>
  </p>

  <p>
    <a href="https://github.com/Namera22/Group2-1030.git">
      GitHub Repository
    </a>
  </p>

  <p>
    <a href="https://namera22.github.io/Group2-1030/">
      Live Site
    </a>
  </p>

  <p>
    <a href="mailto:info@smartcity.com">
      Email Us
    </a>
  </p>

  <p>&copy; 2026 SmartCity Infrastructure Consultancy</p>

</footer>

</body>
</html>